Universe        = vanilla
Executable      = submit_cat_gen.bash
Output          = OUTPUT/out.$(Cluster).$(Process).txt
Error           = OUTPUT/error.$(Cluster).$(Process).txt
Log             = OUTPUT/log.$(Cluster).$(Process).txt
notification = Never
should_transfer_files = NO
getenv = True
Arguments = $(Process)
Requirements =  TARGET.FileSystemDomain == "calx090.ast.cam.ac.uk"
Request_memory = 200000
Request_cpus = 10
stream_output = True
OnExitRemove = (ExitStatus == 0)
Queue 1
